Update advanced.md
olets/zsh-abbr-v4-docs pull request #1
Opened 2023-05-15 06:50 UTC by pimvh

Hi! Thanks for this nice plugin, I was having some trouble activation the highlighting, because I missed this part of the `zsh-syntax-highlighting` docs. 

I think it might be useful to include something like this, or similar in the documentation to make people aware that you also have to do this.

2023-05-21 18:21 UTC, olets requested changes
Thanks for the contribution! This is a great catch.

Let's tighten it up. How about instead

1. Replace the existing `[zsh character highlighting](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting)` with `[zsh regexp highlighter](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/regexp.md)`
2. Add `ZSH_HIGHLIGHT_HIGHLIGHTERS+=(regexp)` to the start of the Linux and macOS snippets

2023-05-24 10:21 UTC, pimvh commented
> Thanks for the contribution! This is a great catch.
> 
> Let's tighten it up. How about instead
> 
>     1. Replace the existing `[zsh character highlighting](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Character-Highlighting)` with `[zsh regexp highlighters](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/regexp.md)`
> 
>     2. Add `ZSH_HIGHLIGHT_HIGHLIGHTERS+=(regexp)` to the start of the Linux snippet and to the start of the macOS snippet

Thanks for the review, I've cleaned up it up as requested.

2023-06-04 02:45 UTC, olets approved these changes
Thank you for the catch and the contibution! I added a small edit

2023-06-04 02:47 UTC, merged

2023-06-04 03:15 UTC, olets commented
I've added the equivalent change to the v5 (latest) docs
- https://github.com/olets/zsh-abbr-v5-docs/commit/697dd3121cad92cf3e1a673604611a4183635b21
- https://zsh-abbr.olets.dev/advanced.html#zsh-syntax-highlighting

2023-06-04 03:21 UTC, olets commented
@pimvh let me know if you'd like to be added as a community contributor (I would have the all-contributors bot add you to https://github.com/olets/zsh-abbr#community and https://zsh-abbr.olets.dev/community/)

2023-06-05 12:31 UTC, pimvh commented
> @pimvh let me know if you'd like to be added as a community contributor (I would have the all-contributors bot add you to [olets/zsh-abbr#community](https://github.com/olets/zsh-abbr#community) and [zsh-abbr.olets.dev/community](https://zsh-abbr.olets.dev/community/))

sure!